apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: images
          image: adomeika94/modosdesign-images
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-access
                  key: S3_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: images-srv
spec:
  selector:
    app: images
  ports:
    - name: images
      protocol: TCP
      port: 3000
      targetPort: 3000
